email:
  sent_from : "<sender_email>" 
  email_password : "<sender_password>"

  # [edit] enter receiver email details
  to : ["<receiver_email_id>"]

area_info:
# [edit] enter your district code or pincode(s)
  __district_code : "<district_code>" 
  __pincode : ["pincode_1", "pincode_2", "pincode_n"]
  
age_limit:
  age_limit : [18, 45]
